### ISSUE TITLE
Error on ILike

### ISSUE THREAD

**Issue by eMerzh** [EnterpriseDB/mysql_fdw#50] opened 2015-03-21 21:28 UTC
hi, i tried to run a query with a ilike but it seems to fail

```SQL
select * from remote_mysql_table where name ilike '%hello%'
```

i got 

```
ERROR:  failed to prepare the MySQL query: 
You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near '~~* '%hello%'))' at line 1
********** Error **********

ERROR: failed to prepare the MySQL query: 
You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near '~~* '%hello%'))' at line 1
State SQL :HV00L
```

**Comment by ibrarahmad** [comment] 2015-04-02 10:33
It works fine on my computer, can you please share the schema of  remote_mysql_table table.

postgres=# SELECt * from msq WHERE b ILike '%foo%';
 a |  b  
---+-----
 1 | foo
(1 row)

**Comment by ahsanhadi** [comment] 2015-04-14 11:40
Closing this case, as the issue is not reproducible...

**Closed by ahsanhadi** 2015-04-14 11:40 UTC
